name: Sandbox CI CD
on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Use deployment placeholder'
        type: boolean 
        required: true
      environment:
        description: 'Deployment environment'
        required: true 
        type: choice
        options:
          - SBX 


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ts-sample

    steps:

      - uses: actions/checkout@v4
      
      - run: |
          echo "::notice file=app.js,line=1,title=YOUR-TITLE::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
          echo "::notice title=NOTICE-02-EXAMPLE::Only title in the notice, no file or line"
          echo -e "\033[1;33mTest yellow"
        name: Echo samples  

      - run: |
          echo "dryrun: ${{ inputs.dryrun }}"
          echo "Environment: ${{ inputs.environment }}"
        name: Workflow Inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}      


      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache-dependency-path: ./ts-sample/yarn.lock
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      -  name: Build
         run: yarn build

      - run: ls
      -  name: Run application
         run: yarn run-app