name: Sandbox CI CD
on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Use deployment placeholder'
        type: boolean 
        required: true
      environment:
        description: 'Deployment environment'
        required: true 
        type: choice
        options:
          - SBX 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "::warning file=app.js,line=1::Missing semicolon"
          echo "::notice file=app.js,line=1::Missing semicolon"
        name: Echo samples  

      - run: |
          echo "dryrun: ${{ inputs.dryrun }}"
          echo "Environment: ${{ inputs.environment }}"
        name: Workflow Inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}      