name: Sandbox CI CD
on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Use deployment placeholder'
        required: true
      environment:
        description: 'Deployment environment'
        required: true 
        type: choice
        options:
          - SBX 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world!" 